package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// TODO: Auto-generated Javadoc
/**
 * Accounts generated by hbm2java.
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "accounts", uniqueConstraints = { @UniqueConstraint(columnNames = "phoneNumber"),
		@UniqueConstraint(columnNames = "accountName"), @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "idCard") })
public class Accounts implements java.io.Serializable {

	/** The id. */
	private int id;

	/** The ward. */
	private Ward ward;

	/** The id card. */
	private String idCard;

	/** The name. */
	private String name;

	/** The birthday. */
	private Date birthday;

	/** The gender. */
	private Boolean gender;

	/** The phone number. */
	private String phoneNumber;

	/** The email. */
	private String email;

	/** The address. */
	private String address;

	/** The account name. */
	private String accountName;

	/** The is admin. */
	private Boolean isAdmin;

	/** The password. */
	private String password;

	/** The is delete. */
	private Boolean isDelete;

	/** The description. */
	private String description;

	/** The store account. */
	private Set<StoreAccount> storeAccount = new HashSet<StoreAccount>(0);

	/**
	 * Instantiates a new accounts.
	 */
	public Accounts() {
	}

	/**
	 * Instantiates a new accounts.
	 *
	 * @param id
	 *            the id
	 */
	public Accounts(int id) {
		this.id = id;
	}

	public Accounts(int id, Ward ward, String idCard, String name, Date birthday, Boolean gender, String phoneNumber,
			String email, String address, String accountName, Boolean isAdmin, String password, Boolean isDelete,
			String description, Set<StoreAccount> storeAccount) {
		super();
		this.id = id;
		this.ward = ward;
		this.idCard = idCard;
		this.name = name;
		this.birthday = birthday;
		this.gender = gender;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.address = address;
		this.accountName = accountName;
		this.isAdmin = isAdmin;
		this.password = password;
		this.isDelete = isDelete;
		this.description = description;
		this.storeAccount = storeAccount;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id
	 *            the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the ward.
	 *
	 * @return the ward
	 */
	@ManyToOne
	@JoinColumn(name = "wardId")
	public Ward getWard() {
		return this.ward;
	}

	/**
	 * Sets the ward.
	 *
	 * @param ward
	 *            the new ward
	 */
	public void setWard(Ward ward) {
		this.ward = ward;
	}

	/**
	 * Gets the id card.
	 *
	 * @return the id card
	 */
	@Column(name = "idCard", unique = true, length = 12)
	public String getIdCard() {
		return this.idCard;
	}

	/**
	 * Sets the id card.
	 *
	 * @param idCard
	 *            the new id card
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name
	 *            the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the birthday.
	 *
	 * @return the birthday
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	/**
	 * Sets the birthday.
	 *
	 * @param birthday
	 *            the new birthday
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * Gets the gender.
	 *
	 * @return the gender
	 */
	@Column(name = "gender")
	public Boolean getGender() {
		return this.gender;
	}

	/**
	 * Sets the gender.
	 *
	 * @param gender
	 *            the new gender
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * Gets the phone number.
	 *
	 * @return the phone number
	 */
	@Column(name = "phoneNumber", unique = true, length = 12)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	/**
	 * Sets the phone number.
	 *
	 * @param phoneNumber
	 *            the new phone number
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * Gets the email.
	 *
	 * @return the email
	 */
	@Column(name = "email", unique = true, length = 30)
	public String getEmail() {
		return this.email;
	}

	/**
	 * Sets the email.
	 *
	 * @param email
	 *            the new email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Gets the address.
	 *
	 * @return the address
	 */
	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	/**
	 * Sets the address.
	 *
	 * @param address
	 *            the new address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Gets the account name.
	 *
	 * @return the account name
	 */
	@Column(name = "accountName", unique = true)
	public String getAccountName() {
		return this.accountName;
	}

	/**
	 * Sets the account name.
	 *
	 * @param accountName
	 *            the new account name
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * Gets the checks if is admin.
	 *
	 * @return the checks if is admin
	 */
	@Column(name = "isAdmin")
	public Boolean getIsAdmin() {
		return this.isAdmin;
	}

	/**
	 * Sets the checks if is admin.
	 *
	 * @param isAdmin
	 *            the new checks if is admin
	 */
	public void setIsAdmin(Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	/**
	 * Gets the password.
	 *
	 * @return the password
	 */
	@Column(name = "password", length = 35)
	public String getPassword() {
		return this.password;
	}

	/**
	 * Sets the password.
	 *
	 * @param password
	 *            the new password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Gets the checks if is delete.
	 *
	 * @return the checks if is delete
	 */
	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * Sets the checks if is delete.
	 *
	 * @param isDelete
	 *            the new checks if is delete
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description
	 *            the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the store account.
	 *
	 * @return the store account
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<StoreAccount> getStoreAccount() {
		return storeAccount;
	}

	/**
	 * Sets the store account.
	 *
	 * @param storeAccount
	 *            the new store account
	 */
	public void setStoreAccount(Set<StoreAccount> storeAccount) {
		this.storeAccount = storeAccount;
	}

}
