package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * GroupDesk generated by hbm2java.
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "groupDesk")
public class GroupDesk implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The name. */
	private String name;
	
	/** The cost. */
	private BigDecimal cost;
	
	/** The is delete. */
	private Boolean isDelete;
	
	/** The description. */
	private String description;
	
	/** The desks. */
	private Set<Desk> desks = new HashSet<Desk>(0);

	/**
	 * Instantiates a new group desk.
	 */
	public GroupDesk() {
	}

	/**
	 * Instantiates a new group desk.
	 *
	 * @param id the id
	 * @param name the name
	 * @param cost the cost
	 */
	public GroupDesk(int id, String name, BigDecimal cost) {
		this.id = id;
		this.name = name;
		this.cost = cost;
	}

	/**
	 * Instantiates a new group desk.
	 *
	 * @param id the id
	 * @param name the name
	 * @param cost the cost
	 * @param isDelete the is delete
	 * @param description the description
	 * @param desks the desks
	 */
	public GroupDesk(int id, String name, BigDecimal cost, Boolean isDelete, String description,
			Set<Desk> desks) {
		this.id = id;
		this.name = name;
		this.cost = cost;
		this.isDelete = isDelete;
		this.description = description;
		this.desks = desks;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the cost.
	 *
	 * @return the cost
	 */
	@Column(name = "cost", nullable = false, scale = 4)
	public BigDecimal getCost() {
		return this.cost;
	}

	/**
	 * Sets the cost.
	 *
	 * @param cost the new cost
	 */
	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	/**
	 * Gets the checks if is delete.
	 *
	 * @return the checks if is delete
	 */
	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * Sets the checks if is delete.
	 *
	 * @param isDelete the new checks if is delete
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the desks.
	 *
	 * @return the desks
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupDesk")
	public Set<Desk> getDesks() {
		return this.desks;
	}

	/**
	 * Sets the desks.
	 *
	 * @param desks the new desks
	 */
	public void setDesks(Set<Desk> desks) {
		this.desks = desks;
	}

}
