package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Material generated by hbm2java.
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "material")
public class Material implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The material type. */
	private MaterialType materialType;
	
	/** The name. */
	private String name;
	
	/** The price. */
	private BigDecimal price;
	
	
	/** The is delete. */
	private Boolean isDelete;
	
	/** The description. */
	private String description;
	
	/** The warehouses. */
	private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);

	/**
	 * Instantiates a new material.
	 */
	public Material() {
	}

	/**
	 * Instantiates a new material.
	 *
	 * @param id the id
	 * @param materialType the material type
	 * @param name the name
	 * @param price the price
	 */
	public Material(int id, MaterialType materialType, String name, BigDecimal price) {
		this.id = id;
		this.materialType = materialType;
		this.name = name;
		this.price = price;
	}

	/**
	 * Instantiates a new material.
	 *
	 * @param id the id
	 * @param materialType the material type
	 * @param name the name
	 * @param price the price
	 * @param storeId the store id
	 * @param isDelete the is delete
	 * @param description the description
	 * @param warehouses the warehouses
	 */
	public Material(int id, MaterialType materialType, String name, BigDecimal price, 
			Boolean isDelete, String description, Set<Warehouse> warehouses) {
		this.id = id;
		this.materialType = materialType;
		this.name = name;
		this.price = price;
		this.isDelete = isDelete;
		this.description = description;
		this.warehouses = warehouses;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the material type.
	 *
	 * @return the material type
	 */
	@ManyToOne
	@JoinColumn(name = "materialTypeId", nullable = false)
	public MaterialType getMaterialType() {
		return this.materialType;
	}

	/**
	 * Sets the material type.
	 *
	 * @param materialType the new material type
	 */
	public void setMaterialType(MaterialType materialType) {
		this.materialType = materialType;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the price.
	 *
	 * @return the price
	 */
	@Column(name = "price", nullable = false, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	/**
	 * Sets the price.
	 *
	 * @param price the new price
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * Gets the checks if is delete.
	 *
	 * @return the checks if is delete
	 */
	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * Sets the checks if is delete.
	 *
	 * @param isDelete the new checks if is delete
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the warehouses.
	 *
	 * @return the warehouses
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	public Set<Warehouse> getWarehouses() {
		return this.warehouses;
	}

	/**
	 * Sets the warehouses.
	 *
	 * @param warehouses the new warehouses
	 */
	public void setWarehouses(Set<Warehouse> warehouses) {
		this.warehouses = warehouses;
	}

}
