package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * Order generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "orders")
public class Orders implements java.io.Serializable {

	private int id;
	private Customer customer;
	private Desk desk;
	private Date date;
	private BigDecimal totalBill;
	private Boolean isDelete;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public Orders() {
	}

	public Orders(int id, Customer customer, Desk desk, BigDecimal totalBill) {
		this.id = id;
		this.customer = customer;
		this.desk = desk;
		this.totalBill = totalBill;
	}

	public Orders(int id, Customer customer, Desk desk, Date date, BigDecimal totalBill, Boolean isDelete,
			Set<OrderDetail> orderDetails) {
		this.id = id;
		this.customer = customer;
		this.desk = desk;
		this.date = date;
		this.totalBill = totalBill;
		this.isDelete = isDelete;
		this.orderDetails = orderDetails;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "customerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne
	@JoinColumn(name = "deskId", nullable = false)
	public Desk getDesk() {
		return this.desk;
	}

	public void setDesk(Desk desk) {
		this.desk = desk;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "totalBill", nullable = false, scale = 4)
	public BigDecimal getTotalBill() {
		return this.totalBill;
	}

	public void setTotalBill(BigDecimal totalBill) {
		this.totalBill = totalBill;
	}

	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "order")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
