package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
// TODO: Auto-generated Javadoc

/**
 * OrderDetail generated by hbm2java.
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "orderDetail")
public class OrderDetail implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The order. */
	private Order order;
	
	/** The product. */
	private Product product;
	
	/** The quantity. */
	private int quantity;
	
	/** The is delete. */
	private Boolean isDelete;
	
	/** The description. */
	private String description;

	/**
	 * Instantiates a new order detail.
	 */
	public OrderDetail() {
	}

	/**
	 * Instantiates a new order detail.
	 *
	 * @param id the id
	 * @param order the order
	 * @param product the product
	 * @param quantity the quantity
	 */
	public OrderDetail(int id, Order order, Product product, int quantity) {
		this.id = id;
		this.order = order;
		this.product = product;
		this.quantity = quantity;
	}

	/**
	 * Instantiates a new order detail.
	 *
	 * @param id the id
	 * @param order the order
	 * @param product the product
	 * @param quantity the quantity
	 * @param isDelete the is delete
	 * @param description the description
	 */
	public OrderDetail(int id, Order order, Product product, int quantity, Boolean isDelete, String description) {
		this.id = id;
		this.order = order;
		this.product = product;
		this.quantity = quantity;
		this.isDelete = isDelete;
		this.description = description;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the order.
	 *
	 * @return the order
	 */
	@ManyToOne
	@JoinColumn(name = "orderId", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	/**
	 * Sets the order.
	 *
	 * @param order the new order
	 */
	public void setOrder(Order order) {
		this.order = order;
	}

	/**
	 * Gets the product.
	 *
	 * @return the product
	 */
	@ManyToOne
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Sets the product.
	 *
	 * @param product the new product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Gets the quantity.
	 *
	 * @return the quantity
	 */
	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	/**
	 * Sets the quantity.
	 *
	 * @param quantity the new quantity
	 */
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	/**
	 * Gets the checks if is delete.
	 *
	 * @return the checks if is delete
	 */
	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * Sets the checks if is delete.
	 *
	 * @param isDelete the new checks if is delete
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
