package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
// TODO: Auto-generated Javadoc

/**
 * PromotionDetail generated by hbm2java.
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "promotionDetail", uniqueConstraints = @UniqueConstraint(columnNames = {
		"productId", "promotionId" }))
public class PromotionDetail implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The product. */
	private Product product;
	
	/** The promotion. */
	private Promotion promotion;
	
	/** The discount. */
	private Integer discount;
	
	/** The is delete. */
	private Boolean isDelete;
	
	/** The description. */
	private String description;

	/**
	 * Instantiates a new promotion detail.
	 */
	public PromotionDetail() {
	}

	/**
	 * Instantiates a new promotion detail.
	 *
	 * @param id the id
	 * @param product the product
	 * @param promotion the promotion
	 */
	public PromotionDetail(int id, Product product, Promotion promotion) {
		this.id = id;
		this.product = product;
		this.promotion = promotion;
	}

	/**
	 * Instantiates a new promotion detail.
	 *
	 * @param id the id
	 * @param product the product
	 * @param promotion the promotion
	 * @param discount the discount
	 * @param isDelete the is delete
	 * @param description the description
	 */
	public PromotionDetail(int id, Product product, Promotion promotion, Integer discount, Boolean isDelete,
			String description) {
		this.id = id;
		this.product = product;
		this.promotion = promotion;
		this.discount = discount;
		this.isDelete = isDelete;
		this.description = description;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the product.
	 *
	 * @return the product
	 */
	@ManyToOne
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Sets the product.
	 *
	 * @param product the new product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Gets the promotion.
	 *
	 * @return the promotion
	 */
	@ManyToOne
	@JoinColumn(name = "promotionId", nullable = false)
	public Promotion getPromotion() {
		return this.promotion;
	}

	/**
	 * Sets the promotion.
	 *
	 * @param promotion the new promotion
	 */
	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	/**
	 * Gets the discount.
	 *
	 * @return the discount
	 */
	@Column(name = "discount")
	public Integer getDiscount() {
		return this.discount;
	}

	/**
	 * Sets the discount.
	 *
	 * @param discount the new discount
	 */
	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	/**
	 * Gets the checks if is delete.
	 *
	 * @return the checks if is delete
	 */
	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * Sets the checks if is delete.
	 *
	 * @param isDelete the new checks if is delete
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
