package com.fsoft.coffeesystem.entity;

// Generated 11-Jan-2017 22:33:33 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Warehouse generated by hbm2java.
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "warehouse")
public class Warehouse implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The material. */
	private Material material;
	
	/** The store. */
	private Store store;
	
	/** The quantity. */
	private Integer quantity;
	
	
	/** The is delete. */
	private Boolean isDelete;
	
	/** The description. */
	private String description;

	/**
	 * Instantiates a new warehouse.
	 */
	public Warehouse() {
	}

	/**
	 * Instantiates a new warehouse.
	 *
	 * @param id the id
	 * @param material the material
	 */
	public Warehouse(int id, Material material) {
		this.id = id;
		this.material = material;
	}

	/**
	 * Instantiates a new warehouse.
	 *
	 * @param id the id
	 * @param material the material
	 * @param store the store
	 * @param quantity the quantity
	 * @param hide the hide
	 * @param isDelete the is delete
	 * @param description the description
	 */
	public Warehouse(int id, Material material, Store store, Integer quantity, Boolean isDelete,
			String description) {
		this.id = id;
		this.material = material;
		this.store = store;
		this.quantity = quantity;
		this.isDelete = isDelete;
		this.description = description;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the material.
	 *
	 * @return the material
	 */
	@ManyToOne
	@JoinColumn(name = "materialId", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	/**
	 * Sets the material.
	 *
	 * @param material the new material
	 */
	public void setMaterial(Material material) {
		this.material = material;
	}

	/**
	 * Gets the store.
	 *
	 * @return the store
	 */
	@ManyToOne
	@JoinColumn(name = "storeId")
	public Store getStore() {
		return this.store;
	}

	/**
	 * Sets the store.
	 *
	 * @param store the new store
	 */
	public void setStore(Store store) {
		this.store = store;
	}

	/**
	 * Gets the quantity.
	 *
	 * @return the quantity
	 */
	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	/**
	 * Sets the quantity.
	 *
	 * @param quantity the new quantity
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}


	/**
	 * Gets the checks if is delete.
	 *
	 * @return the checks if is delete
	 */
	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * Sets the checks if is delete.
	 *
	 * @param isDelete the new checks if is delete
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
